import { Client, Vehicle, Order, InventoryItem, FinanceTransaction } from '../types';

export const initialClients: Client[] = [
  {
    id: 'client-1',
    name: 'Олександр Мельник',
    phone: '+380 67 452 1189',
    notes: 'Постійний клієнт. Просить зберігати заводські зазори та фарбувати під товщиномір.',
    createdAt: '2024-04-10T09:30:00Z',
  },
  {
    id: 'client-2',
    name: 'Тарас Коваленко',
    phone: '+380 50 891 3340',
    notes: 'Перекуп, часто привозить авто з США на відновлення. Завжди платить готівкою.',
    createdAt: '2024-04-18T14:15:00Z',
  },
  {
    id: 'client-3',
    name: 'Ірина Шевченко',
    phone: '+380 93 234 5678',
    notes: 'Притерла бампер на парковці. Просила зробити без видимого переходу.',
    createdAt: '2024-05-02T11:00:00Z',
  },
  {
    id: 'client-4',
    name: 'Сергій Бондар',
    phone: '+380 97 789 4412',
    notes: 'Власник автопарку доставки. Потрібен швидкий оборот та якісна антикорозійна обробка.',
    createdAt: '2024-05-15T16:20:00Z',
  },
  {
    id: 'client-5',
    name: 'Володимир Дяченко',
    phone: '+380 68 331 9055',
    notes: 'Порадив колега з СТО. Цікавить повне перефарбування з розбиранням.',
    createdAt: '2024-06-01T10:45:00Z',
  },
];

export const initialVehicles: Vehicle[] = [
  {
    id: 'veh-1',
    clientId: 'client-1',
    make: 'Volkswagen',
    model: 'Passat B8',
    licensePlate: 'КА 5421 ВІ',
    vin: 'WVWZZZ3CZHE129482',
    year: 2018,
    colorName: 'Чорний перламутр',
    colorCode: 'LC9X (Deep Black)',
    notes: 'Фарбування капота та бампера без переходу на крила.',
    createdAt: '2024-04-10T09:40:00Z',
  },
  {
    id: 'veh-2',
    clientId: 'client-2',
    make: 'BMW',
    model: '530d (G30)',
    licensePlate: 'АА 9920 СТ',
    vin: 'WBAJC91090G339101',
    year: 2020,
    colorName: 'Темно-сірий металік',
    colorCode: 'C2Y (Bluestone)',
    notes: 'Удар по правій стороні: крило, 2 дверки, поріг. Рихтування та малювання.',
    createdAt: '2024-04-18T14:30:00Z',
  },
  {
    id: 'veh-3',
    clientId: 'client-3',
    make: 'Toyota',
    model: 'RAV4',
    licensePlate: 'ВХ 1184 ЕР',
    vin: 'JTMEFREV00D091238',
    year: 2021,
    colorName: 'Білий перламутр (3-шар)',
    colorCode: '070 (Blizzard Pearl)',
    notes: 'Складний тришаровий колір. Потрібно зробити викраски перед нанесенням.',
    createdAt: '2024-05-02T11:20:00Z',
  },
  {
    id: 'veh-4',
    clientId: 'client-4',
    make: 'Renault',
    model: 'Master',
    licensePlate: 'АІ 3044 ОО',
    vin: 'VF1MA000356199341',
    year: 2019,
    colorName: 'Білий акрил',
    colorCode: 'OV369 (Blanc Glacier)',
    notes: 'Комерційне авто. Фарбування розсувних дверей та задніх арок.',
    createdAt: '2024-05-15T16:30:00Z',
  },
  {
    id: 'veh-5',
    clientId: 'client-5',
    make: 'Audi',
    model: 'A6 (C7)',
    licensePlate: 'ВС 7712 НЕ',
    vin: 'WAUZZZ4G9CN044519',
    year: 2016,
    colorName: 'Сріблястий металік',
    colorCode: 'LX7W (Ice Silver)',
    notes: 'Сколи на арках та порогах, потрібна локальна реставрація та бронеплівка.',
    createdAt: '2024-06-01T11:00:00Z',
  },
];

export const initialInventory: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Лак акриловий Roberlo Kronox 610 UHS (1л + 0.5л)',
    category: 'clearcoats',
    unit: 'комплект',
    quantity: 6,
    minQuantity: 2,
    price: 1450,
    supplier: 'АвтоФарби Київ',
    notes: 'Швидка сушка (10 хв при 60°C). Відмінний глянець.',
    updatedAt: '2024-06-10T12:00:00Z',
  },
  {
    id: 'inv-2',
    name: 'Лак Duxone DX44 2K HS (1л + затв.)',
    category: 'clearcoats',
    unit: 'комплект',
    quantity: 4,
    minQuantity: 3,
    price: 980,
    supplier: 'Спектр-Плюс',
    notes: 'Універсальний лак для щоденних замовлень.',
    updatedAt: '2024-06-08T10:00:00Z',
  },
  {
    id: 'inv-3',
    name: 'Грунт акриловий Novol Protect 310 4:1 (Сірий, 1л)',
    category: 'primers',
    unit: 'л',
    quantity: 5,
    minQuantity: 2,
    price: 680,
    supplier: 'АвтоФарби Київ',
    notes: 'Хороша наповнюваність, легко шліфується.',
    updatedAt: '2024-06-05T09:00:00Z',
  },
  {
    id: 'inv-4',
    name: 'Грунт епоксидний антикорозійний APP 1:1',
    category: 'primers',
    unit: 'л',
    quantity: 1,
    minQuantity: 2,
    price: 850,
    supplier: 'АвтоЕмалі Захід',
    notes: 'УВАГА: Залишився 1 літр! Необхідно дозамовити.',
    updatedAt: '2024-06-12T15:00:00Z',
  },
  {
    id: 'inv-5',
    name: 'Шпаклівка з алюмінієвим пилом Troton Alu (1.8 кг)',
    category: 'putties',
    unit: 'банка',
    quantity: 3,
    minQuantity: 1,
    price: 490,
    supplier: 'Спектр-Плюс',
    notes: 'Для деталей з підвищеним температурним навантаженням (капоти).',
    updatedAt: '2024-06-01T11:30:00Z',
  },
  {
    id: 'inv-6',
    name: 'Шпаклівка фінішна Novol Finish (1.0 кг)',
    category: 'putties',
    unit: 'банка',
    quantity: 4,
    minQuantity: 2,
    price: 360,
    supplier: 'АвтоФарби Київ',
    notes: 'Ідеальне виведення дрібних пор.',
    updatedAt: '2024-06-07T14:20:00Z',
  },
  {
    id: 'inv-7',
    name: 'Абразивні круги 3M Hookit 260L P400 (d150)',
    category: 'abrasives',
    unit: 'пачка',
    quantity: 1,
    minQuantity: 2,
    price: 1100,
    supplier: '3M Україна',
    notes: 'Мало! Критичний залишок для підготовки деталей.',
    updatedAt: '2024-06-14T08:15:00Z',
  },
  {
    id: 'inv-8',
    name: 'Абразивні круги Mirka Abranet P800',
    category: 'abrasives',
    unit: 'пачка',
    quantity: 2,
    minQuantity: 1,
    price: 950,
    supplier: 'Спектр-Плюс',
    notes: 'Сітчастий абразив під мокре/сухе матування.',
    updatedAt: '2024-05-28T16:00:00Z',
  },
  {
    id: 'inv-9',
    name: 'Скотч малярний термостійкий Tesa 38мм x 50м (110°C)',
    category: 'masking',
    unit: 'рулон',
    quantity: 12,
    minQuantity: 5,
    price: 140,
    supplier: 'АвтоФарби Київ',
    notes: 'Не залишає слідів клею в сушильній камері.',
    updatedAt: '2024-06-11T13:00:00Z',
  },
  {
    id: 'inv-10',
    name: 'Знежирювач антисилікон APP W900 (5л)',
    category: 'chemicals',
    unit: 'каністра',
    quantity: 2,
    minQuantity: 1,
    price: 720,
    supplier: 'АвтоФарби Київ',
    notes: 'Очищення та знежирення поверхні перед нанесенням ЛФМ.',
    updatedAt: '2024-05-20T10:00:00Z',
  },
  {
    id: 'inv-11',
    name: 'Базова емаль (комп\'ютерний підбір) 100г',
    category: 'paints',
    unit: 'порція',
    quantity: 8,
    minQuantity: 3,
    price: 380,
    supplier: 'Колорист-Лаб',
    notes: 'Індивідуальний підбір фарби за лючком бензобака.',
    updatedAt: '2024-06-13T17:00:00Z',
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ord-1',
    orderNumber: 'AP-2024-051',
    clientId: 'client-1',
    vehicleId: 'veh-1',
    date: '2024-06-10',
    deadlineDate: '2024-06-17',
    status: 'painting',
    works: [
      {
        id: 'w-1',
        category: 'Підготовка та пофарбування',
        title: 'Пофарбування бампера',
        price: 10000,
        materialCost: 2000,
        helperSalary: 4000,
        painterSalary: 4000,
      },
      {
        id: 'w-2',
        category: 'Підготовка та пофарбування',
        title: 'Пофарбування крила',
        price: 8000,
        materialCost: 1600,
        helperSalary: 3200,
        painterSalary: 3200,
      },
      {
        id: 'w-3',
        category: 'Рихтувальні роботи',
        title: 'Ремонт крила правого',
        price: 4000,
        materialCost: 600,
        helperSalary: 1700,
        painterSalary: 1700,
      },
      {
        id: 'w-4',
        category: 'Слюсарні роботи',
        title: 'Демонтаж-монтаж деталей',
        price: 2500,
        materialCost: 300,
        helperSalary: 1100,
        painterSalary: 1100,
      },
    ],
    materials: [
      { id: 'm-1', inventoryId: 'inv-1', name: 'Лак Roberlo Kronox 610 UHS', quantity: 1, unit: 'комплект', price: 1450, total: 1450 },
      { id: 'm-2', inventoryId: 'inv-11', name: 'Базова емаль LC9X підбір 450г', quantity: 4.5, unit: 'порція (100г)', price: 380, total: 1710 },
      { id: 'm-3', inventoryId: 'inv-3', name: 'Грунт акриловий Novol Protect 310', quantity: 0.5, unit: 'л', price: 680, total: 340 },
    ],
    totalAmount: 28000,
    paidAmount: 18000,
    remainingAmount: 10000,
    notes: 'Клієнт вніс аванс 18000 ₴. Залишок 10000 ₴ при видачі авто.',
    createdAt: '2024-06-10T10:00:00Z',
  },
  {
    id: 'ord-2',
    orderNumber: 'AP-2024-052',
    clientId: 'client-2',
    vehicleId: 'veh-2',
    date: '2024-06-11',
    deadlineDate: '2024-06-20',
    status: 'preparation',
    works: [
      { id: 'w-5', category: 'Рихтувальні роботи', title: 'Рихтування правого переднього крила на стапелі', price: 3500, materialCost: 500, helperSalary: 1500, painterSalary: 1500 },
      { id: 'w-6', category: 'Слюсарні роботи', title: 'Демонтаж та розбирання правих дверей', price: 1800, materialCost: 200, helperSalary: 800, painterSalary: 800 },
      { id: 'w-7', category: 'Підготовка та пофарбування', title: 'Фарбування крила переднього правого', price: 3800, materialCost: 1200, helperSalary: 1300, painterSalary: 1300 },
      { id: 'w-8', category: 'Підготовка та пофарбування', title: 'Фарбування дверей передніх правих з переходом', price: 4000, materialCost: 1000, helperSalary: 1500, painterSalary: 1500 },
      { id: 'w-9', category: 'Підготовка та пофарбування', title: 'Фарбування дверей задніх правих', price: 3800, materialCost: 1000, helperSalary: 1400, painterSalary: 1400 },
      { id: 'w-10', category: 'Рихтувальні роботи', title: 'Фарбування та витягування порога', price: 2900, materialCost: 700, helperSalary: 1100, painterSalary: 1100 },
    ],
    materials: [
      { id: 'm-4', inventoryId: 'inv-5', name: 'Шпаклівка Troton Alu', quantity: 1, unit: 'банка', price: 490, total: 490 },
      { id: 'm-5', inventoryId: 'inv-4', name: 'Грунт епоксидний APP', quantity: 1, unit: 'л', price: 850, total: 850 },
      { id: 'm-6', inventoryId: 'inv-1', name: 'Лак Roberlo Kronox 610 UHS', quantity: 2, unit: 'комплект', price: 1450, total: 2900 },
      { id: 'm-7', inventoryId: 'inv-11', name: 'Фарба підбір C2Y (800г)', quantity: 8, unit: 'порція (100г)', price: 380, total: 3040 },
    ],
    totalAmount: 25280,
    paidAmount: 15000,
    remainingAmount: 10280,
    notes: 'Великий проект. Аванс 15000 ₴ отримано на картку.',
    createdAt: '2024-06-11T12:30:00Z',
  },
  {
    id: 'ord-3',
    orderNumber: 'AP-2024-053',
    clientId: 'client-3',
    vehicleId: 'veh-3',
    date: '2024-06-12',
    deadlineDate: '2024-06-15',
    status: 'polishing',
    works: [
      { id: 'w-11', category: 'Підготовка та пофарбування', title: 'Локальний ремонт та фарбування кута заднього бампера', price: 2800, materialCost: 800, helperSalary: 1000, painterSalary: 1000 },
      { id: 'w-12', category: 'Детейлінг та полірування', title: 'Фінішне полірування переходу та нанесення захисного воску', price: 900, materialCost: 200, helperSalary: 350, painterSalary: 350 },
    ],
    materials: [
      { id: 'm-8', inventoryId: 'inv-2', name: 'Лак Duxone DX44', quantity: 0.5, unit: 'комплект', price: 980, total: 490 },
      { id: 'm-9', inventoryId: 'inv-11', name: 'Базова фарба тришаровий білий перламутр 070 (200г)', quantity: 2, unit: 'порція (100г)', price: 450, total: 900 },
    ],
    totalAmount: 5090,
    paidAmount: 5090,
    remainingAmount: 0,
    notes: 'Повністю сплачено. Сьогодні фінішне полірування, видача ввечері.',
    createdAt: '2024-06-12T09:15:00Z',
  },
  {
    id: 'ord-4',
    orderNumber: 'AP-2024-049',
    clientId: 'client-4',
    vehicleId: 'veh-4',
    date: '2024-06-03',
    deadlineDate: '2024-06-08',
    status: 'delivered',
    works: [
      { id: 'w-13', category: 'Слюсарні роботи', title: 'Піскоструйна очистка та антикор арок', price: 2200, materialCost: 600, helperSalary: 800, painterSalary: 800 },
      { id: 'w-14', category: 'Підготовка та пофарбування', title: 'Фарбування двох задніх арок та порогів комерційного буса', price: 4600, materialCost: 1400, helperSalary: 1600, painterSalary: 1600 },
    ],
    materials: [
      { id: 'm-10', inventoryId: 'inv-4', name: 'Грунт епоксидний APP', quantity: 1, unit: 'л', price: 850, total: 850 },
      { id: 'm-11', inventoryId: 'inv-2', name: 'Лак Duxone DX44', quantity: 1, unit: 'комплект', price: 980, total: 980 },
    ],
    totalAmount: 8630,
    paidAmount: 8630,
    remainingAmount: 0,
    notes: 'Роботу здано в строк. Оплата за безготівковим розрахунком на ФОП.',
    createdAt: '2024-06-03T11:00:00Z',
  },
  {
    id: 'ord-5',
    orderNumber: 'AP-2024-054',
    clientId: 'client-5',
    vehicleId: 'veh-5',
    date: '2024-06-14',
    deadlineDate: '2024-06-22',
    status: 'new',
    works: [
      { id: 'w-15', category: 'Слюсарні роботи', title: 'Дефектовка та складання кошторису', price: 0, materialCost: 0, helperSalary: 0, painterSalary: 0 },
      { id: 'w-16', category: 'Підготовка та пофарбування', title: 'Локальний підкрас 4 арок з виведенням корозії', price: 6400, materialCost: 1600, helperSalary: 2400, painterSalary: 2400 },
      { id: 'w-17', category: 'Підготовка та пофарбування', title: 'Фарбування порогів захисним поліуретаном Raptor', price: 5200, materialCost: 1400, helperSalary: 1900, painterSalary: 1900 },
      { id: 'w-18', category: 'Детейлінг та полірування', title: 'Абразивне 3-етапне полірування всього кузова', price: 5500, materialCost: 1100, helperSalary: 2200, painterSalary: 2200 },
    ],
    materials: [
      { id: 'm-12', inventoryId: 'inv-4', name: 'Грунт епоксидний APP', quantity: 1, unit: 'л', price: 850, total: 850 },
      { id: 'm-13', inventoryId: 'inv-8', name: 'Mirka Abranet круги', quantity: 1, unit: 'пачка', price: 950, total: 950 },
    ],
    totalAmount: 18900,
    paidAmount: 5000,
    remainingAmount: 13900,
    notes: 'Авто заїхало в бокс, складено акт прийому. Аванс 5000 ₴.',
    createdAt: '2024-06-14T14:00:00Z',
  },
];

export const initialTransactions: FinanceTransaction[] = [
  {
    id: 'tx-1',
    type: 'income',
    category: 'Аванс замовлення',
    amount: 8000,
    date: '2024-06-10',
    orderId: 'ord-1',
    clientId: 'client-1',
    description: 'Аванс за фарбування VW Passat B8 (AP-2024-051)',
    paymentMethod: 'cash',
    createdAt: '2024-06-10T10:05:00Z',
  },
  {
    id: 'tx-2',
    type: 'expense',
    category: 'Закупівля матеріалів',
    amount: 4350,
    date: '2024-06-10',
    description: 'Закупівля лаку Roberlo та ґрунту Novol (АвтоФарби Київ)',
    paymentMethod: 'card',
    createdAt: '2024-06-10T15:20:00Z',
  },
  {
    id: 'tx-3',
    type: 'income',
    category: 'Аванс замовлення',
    amount: 15000,
    date: '2024-06-11',
    orderId: 'ord-2',
    clientId: 'client-2',
    description: 'Аванс за кузовний ремонт BMW G30 (AP-2024-052)',
    paymentMethod: 'card',
    createdAt: '2024-06-11T12:45:00Z',
  },
  {
    id: 'tx-4',
    type: 'income',
    category: 'Повна оплата',
    amount: 5090,
    date: '2024-06-12',
    orderId: 'ord-3',
    clientId: 'client-3',
    description: 'Оплата за ремонт бампера Toyota RAV4 (AP-2024-053)',
    paymentMethod: 'card',
    createdAt: '2024-06-12T09:30:00Z',
  },
  {
    id: 'tx-5',
    type: 'expense',
    category: 'Електроенергія та тепло',
    amount: 3200,
    date: '2024-06-12',
    description: 'Оплата електроенергії малярної камери та компресора',
    paymentMethod: 'iban',
    createdAt: '2024-06-12T16:00:00Z',
  },
  {
    id: 'tx-6',
    type: 'income',
    category: 'Остаточний розрахунок',
    amount: 8630,
    date: '2024-06-08',
    orderId: 'ord-4',
    clientId: 'client-4',
    description: 'Оплата по акту за Renault Master (AP-2024-049)',
    paymentMethod: 'iban',
    createdAt: '2024-06-08T17:10:00Z',
  },
  {
    id: 'tx-7',
    type: 'expense',
    category: 'Оренда боксу',
    amount: 12000,
    date: '2024-06-01',
    description: 'Оренда малярного цеху та сушильної камери за червень',
    paymentMethod: 'iban',
    createdAt: '2024-06-01T09:00:00Z',
  },
  {
    id: 'tx-8',
    type: 'income',
    category: 'Аванс замовлення',
    amount: 5000,
    date: '2024-06-14',
    orderId: 'ord-5',
    clientId: 'client-5',
    description: 'Аванс за ремонт порогів та арок Audi A6 (AP-2024-054)',
    paymentMethod: 'cash',
    createdAt: '2024-06-14T14:10:00Z',
  },
  {
    id: 'tx-9',
    type: 'expense',
    category: 'Інструмент та обладнання',
    amount: 1850,
    date: '2024-06-13',
    description: 'Ремкомплект для фарбопульта DeVilbiss (сопло 1.3мм)',
    paymentMethod: 'card',
    createdAt: '2024-06-13T11:40:00Z',
  },
];
